use strict;
use warnings;
use Test::More;
use FindBin;
use lib "$FindBin::Bin/../maped";
use Maped qw(command status_text);
my ($rc, $out) = command(2, 1024, $^X, '-e', 'print "ok"');
is($rc, 0, 'successful child');
is($out, 'ok', 'capture output');
($rc, $out) = command(2, 1024, $^X, '-e', 'print "partial"; exit 3');
is(status_text($rc), 'exit 3', 'nonzero exit');
($rc, $out) = command(2, 1024, '/nonexistent/maped-command');
is($rc, -1, 'exec failure');
($rc, $out) = command(2, 1024, $^X, '-e', 'kill 15, $$');
is(status_text($rc), 'signal 15', 'signal is not exit zero');
($rc, $out) = command(0.2, 1024, $^X, '-e', 'sleep 10');
is($rc, -1, 'timeout');
like($out, qr/timed out/, 'timeout diagnostic');
($rc, $out) = command(2, 64, $^X, '-e', 'print "x" x 1000');
is($rc, -1, 'bounded output');
like($out, qr/output limit/, 'output limit diagnostic');
($rc, $out) = command(0.2, 1024, $^X, '-e', 'exit if fork; sleep 10');
is($rc, -1, 'timeout covers descendants holding pipe');
done_testing;
