use strict;
use warnings;
use Test::More;
use FindBin;
use lib "$FindBin::Bin/../maped";
use Maped qw(command status_text parse_lease complete_lease lease_text);
my ($rc, $out) = command(2, 1024, $^X, '-e', 'print "ok"');
is($rc, 0, 'successful child');
is($out, 'ok', 'capture output');
($rc, $out) = command(2, 1024, $^X, '-e', 'print "partial"; exit 3');
is(status_text($rc), 'exit 3', 'nonzero exit');
($rc, $out) = command(2, 1024, '/nonexistent/maped-command');
is($rc, -1, 'exec failure');
($rc, $out) = command(2, 1024, $^X, '-e', 'kill 15, $$');
is(status_text($rc), 'signal 15', 'signal is not exit zero');
($rc, $out) = command(0.2, 1024, $^X, '-e', 'sleep 10');
is($rc, -1, 'timeout');
like($out, qr/timed out/, 'timeout diagnostic');
($rc, $out) = command(2, 64, $^X, '-e', 'print "x" x 1000');
is($rc, -1, 'bounded output');
like($out, qr/output limit/, 'output limit diagnostic');
($rc, $out) = command(0.2, 1024, $^X, '-e', 'exit if fork; sleep 10');
is($rc, -1, 'timeout covers descendants holding pipe');

my $base = "ia_pd 0 2001:db8:100:: 56\nmape_br 2001:db8::1\n";
my $wide = "mape_rule 0 16 192.0.2.0 24 2001:db8:: 32\nmape_portparams 6 8 42\n";
my $narrow = "mape_rule 0 8 198.51.100.0 24 2001:db8:100:: 48\n";
my %lease = parse_lease($base . $wide . $narrow);
is($lease{MAP_IPV4_PREFIX}, '198.51.100.0', 'longest matching BMR');
is($lease{DHCP_PSID_LEN}, 0, 'no port parameters inherited');
is($lease{PSID_OFFSET}, 6, 'default MAP offset');
my %reverse = parse_lease($base . $narrow . $wide);
is_deeply(\%reverse, \%lease, 'BMR selection independent of order');
my %roundtrip = parse_lease(lease_text(\%lease));
delete $roundtrip{portparams_seen};
is_deeply(\%roundtrip, \%lease, 'snapshot round trip');
eval { parse_lease($base . $narrow . $narrow) };
like($@, qr/ambiguous/, 'ambiguous BMR rejected');
eval { parse_lease($base . "mape_portparams 6 8 1\n") };
like($@, qr/without rule/, 'orphan parameters rejected');
my %zero = parse_lease($base . $narrow . "mape_portparams 0 0 123\n");
ok(complete_lease(\%zero), 'zero offset and length are complete');
is($zero{DHCP_PSID}, 0, 'zero-length PSID field ignored');
done_testing;
