#!/bin/ksh
#
# OpenBSD rc.d script for mape-watch.

daemon="/usr/bin/perl"
daemon_flags="/usr/local/sbin/mape-watch -d"
pexp="/usr/bin/perl /usr/local/sbin/mape-watch -d"

. /etc/rc.d/rc.subr

rc_reload=NO

rc_cmd $1
