# maped.conf sample

# FTTH Cosmote values for PPPoE

# Network configuration
WAN_IF="pppoe0"
LEASE_IF="pppoe0"
LAN_NET="{ 192.168.121.0/24, 192.168.122.0/24, 192.168.123.0/24 }"

# gif(4) interface
GIF_IF="gif0"
GIF_MTU="1452"
LEASE_FILE="/var/db/dhcp6leased/pppoe0"
PF_ANCHOR_FILE="/etc/pf.anchors/mape"

# maped(8)
MAPE_STATE_DIR="/var/db/mape"
MAPE_PEER_IPV4="0.0.0.1"
MAPED_UP="/usr/local/libexec/maped/maped-up"
MAPED_DERIVE="/usr/local/libexec/maped/maped-derive"
MAPE_LOG_LEVEL="info"
